### ISSUE TITLE
Genome version label is incorrect

### ISSUE THREAD

**Issue by bwildin-clingen** [broadinstitute/cma-search#1]
It is hg18 and hg18, not hg38 and hg 19.  Which version naming nomenclature are you wanting to use?  hg or GRCh?  The latter uses numbers like 37 and 38, so it is confusing to have as an option on this tool hg38 - that is meaningless.  Thanks for checking it out!

**Comment by bw2** [comment]
UCSC uses "hg19" and "hg38" (for example, here: https://genome.ucsc.edu/cgi-bin/hgGateway).
The main reason I use "hg38" instead of "GRCh38" is because it's shorter : )

**Comment by bwildin-clingen** [comment]
Remains confusing and not consistent with clinical practice guidelines – UCSC is not the correct authority on this. 

 

      Bob

Bob Wildin, MD, ABMG Clinical Geneticist

**Comment by bw2** [comment]
ok, I've updated the labels.

**Comment by bwildin-clingen** [comment]
Thank you! 😊

 

      Bob

Bob Wildin, MD, ABMG Clinical Geneticist
