### ISSUE TITLE
Gene Content Discrepancies 

### ISSUE THREAD

**Issue by zklewis** [broadinstitute/cma-search#2]
Hello,

While searching for genes within a region on chromosome 2, I noticed a discrepancy between the number of genes listed when slightly different search term formats are used. When searching for chr2:30814984-42798684 it lists 5 recessive genes, but if you search CHR2:30814984-42798684 it only lists 1 recessive gene. These are the same chromosome & coordinates with the only difference being that "CHR" is capitalized in one and not the other. Please advise.

**Comment by bw2** [comment]
The code was expecting "chr", and not handling "CHR" correctly. This is fixed now. Also, the data has been updated to the latest version of OMIM, so there are more results now.
